### ISSUE TITLE
Issue when running make install

### ISSUE THREAD

**Issue by awsomenes** [openglonmetal/MGL#1]
When trying to run make install, I get this error: 
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot copy file
  "/Users/*****/MGL/external/SPIRV-Cross/build/libspirv-cross-core.a" to
  "/usr/local/lib/libspirv-cross-core.a": Permission denied.

**Comment by openglonmetal** [comment]
You may have to change your permissions on /usr/local/lib or do a sudo make install

**Comment by awsomenes** [comment]
Yeah, also CmakeLists.txt appears to be missing from the Ezxml because terminal is complaining about that file missing when attempting to run cmake

**Comment by darkaegisagain** [comment]
I think ezxml may be just a makefile build, I just included the source and built it as part of the parser.
