### ISSUE TITLE
Question regarding design

### ISSUE THREAD

**Issue by asdfjkluiop** [openglonmetal/MGL#22]
I have to say this project is very interesting as someone developing a game engine and trying to figure out if macOS support is worth it due to the lack of SSBOs in the native macOS GL4.1 driver which my engine makes use of for several effects. However the design has sort of led me to a question I'd like to ask. What was the reason for building an OpenGL state tracker from scratch as opposed to writing a Gallium3D driver for mesa, which has had a production ready OpenGL implementation for quite some time? I know the mesa team have talked here and there about such a driver although I don't think anyone's put the time into working on one.

**Comment by darkaegisagain** [comment]
Well I looked at Mesa and like the Apple OpenGL it was originally designed as a software renderer and like Apple OpenGL it has become overly complex and bloated.. it looked like a mess.

I worked on Apple OpenGL for 10+ years, I know it can be much simpler. So I implemented a OpenGL shim on top of Metal focused on 4.6 and not being compatible with EGL or legacy calls which would make it complex. With this approach you can use all the new 4.6 features for bindless object calls and less state management user API overhead.

Internally it validates parameters, moves data and sets dirty flags. If it is a execution call like a draw arrays call it updates the metal state and makes the equivalent metal call.

I have measured the overhead and its very small, I think there may be at most a 4% overhead in MGL which is significantly less than what it would have been with a Mesa driver.

If you are interested in developing SSBO’s and other features it’s quite simple to get started using MGL under Xcode, just walk through a few of the calls and a execution call to see what happens. If you need help getting started give me a heads up as I am working on making this a bit more user friendly for more participation.


Cheers

Mike
