### ISSUE TITLE
Using an Organization vs a User account

### ISSUE THREAD

**Issue by magneticflux-** [openglonmetal/MGL#3]
It seems like you created a GitHub user to hold this repository (and possibly related ones in the future). 

From https://docs.github.com/en/get-started/learning-about-github/types-of-github-accounts:
> Tip: Personal accounts are intended for humans, but you can create accounts to automate activity on GitHub. This type of account is called a machine user. For example, you can create a machine user account to automate continuous integration (CI) workflows.

GitHub has a feature designed to group repositories together without being attached to a single user: an Organization. GitHub recommends as best practice to instead have a GitHub user for your person, and then group related community repositories under an organization that you manage.
From https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/about-organizations:
> Your team can collaborate on GitHub by using an organization account. Each person that uses GitHub signs into a user account. Multiple user accounts can collaborate on shared projects by joining the same organization account, which owns the repositories. A subset of these user accounts can be given the role of organization owner, which allows those people to granularly manage access to the organization's resources using sophisticated security and administrative features.

It is possible to convert an existing GitHub user into an organization here: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-user-account-settings/converting-a-user-into-an-organization
I recommend doing this with @openglonmetal and then creating or using existing personal accounts for individuals contributing to the project.

**Comment by darkaegisagain** [comment]
Ok sounds good

**Comment by darkaegisagain** [comment]
Done, if you want to be added to the list of contributors just give me a heads up.
