### ISSUE TITLE
viewport

### ISSUE THREAD

**Issue by conversy** [openglonmetal/MGL#38]
In the course of fixing hidpi support, I managed to get the highest possible rendering quality (i.e. no scaling, no filtering).
However, I recently found that it's only working with some examples (e.g. `test_2D_textures`), and not with others (e.g. `test_2D_array_textures`): the rendering is limited to the upper-left corner of the window.

I could not fix it as of yet. I changed the view port with glViewPort(w*2, h*2) for hidpi, but it's only working with `test_2D_textures`), I do not know why it does not with other examples...

**Comment by dokipen3d** [comment]
I'm seeing the same thing. I might use it as a good challenge to learn how the library works and see if I can find out whats going on.

**Comment by darkaegisagain** [comment]
Thats a good thing… Conversy has been contributing and fixing issues for a while now. The more people that dig into MGL and fix bugs / test / add features the better, that was the primary reason I put it on GitHub.

I have been on vacation in France and sailing in the Pacific Northwest for the last couple of months, I like long vacations… I typically only work on coding in the winter here in the PNW when its raining and there is not much else to do. But I can take a look when I get home tonight.

Cheers,

Mike

**Comment by r58Playz** [comment]
It seems that only the color buffer's size is changed while the depth and stencil buffers remain the same after a glViewport. This is what is causing the issue.

Running `test_mgl_glfw` with Metal API Validation on prints: 
```
validateRenderPassDescriptor:991: failed assertion `RenderPass Descriptor Validation
renderTargetWidth (1200) must be <= minimum attachment width (600).
renderTargetHeight (1200) must be <= minimum attachment height (600).
```

**Comment by dokipen3d** [comment]
I'm new to xcode, how do I run the d e unable with metal app validation ?

**Comment by darkaegisagain** [comment]
I never used it fully,.. I did write some tests in that form but there were a lot of other things to do.. its not too difficult and probably worth doing.

I think the big issue I ran into was to test these you had to run them effectively offscreen and compare the results to golden images, something that was not realistic at the time for me.

Mike

**Comment by r58Playz** [comment]
> I'm new to xcode, how do I run the executable with metal app validation ?
Click on test_mgl_glfw
<img width="179" alt="Screen Shot 2022-07-30 at 7 28 43 AM" src="https://user-images.githubusercontent.com/45221816/181918879-16c11667-8396-46f7-bc03-689c1f1a9343.png">

Select edit scheme
<img width="179" alt="Screen Shot 2022-07-30 at 7 29 01 AM" src="https://user-images.githubusercontent.com/45221816/181918889-909c2103-216b-40b2-9ff3-2d3d4d4e712a.png">

Turn on API Validation
<img width="931" alt="Screen Shot 2022-07-30 at 7 29 17 AM" src="https://user-images.githubusercontent.com/45221816/181918897-c015e328-bd99-4732-9a02-2c004e3078c7.png">

**Comment by darkaegisagain** [comment]
Thats about it, select the executable you want to work with then run it under debug.

I find its more useful than makefile builds as I can walk functions for debugging.

Mike

**Comment by r58Playz** [comment]
Partially fixed
Metal API Validation does not complain anymore
<img width="712" alt="Screen Shot 2022-08-01 at 9 28 21 AM" src="https://user-images.githubusercontent.com/45221816/182198016-97f8cd80-e0b3-488d-b046-8f24dce29733.png">

**Comment by r58Playz** [comment]
<img width="712" alt="Screen Shot 2022-08-01 at 9 40 40 AM" src="https://user-images.githubusercontent.com/45221816/182200018-3c6f100e-8429-4803-b2ed-5bc4cb0b3bdd.png">

The test program needed to multiply the width and height by 2.
