### ISSUE TITLE
Need a Makefile build

### ISSUE THREAD

**Issue by darkaegisagain** [openglonmetal/MGL#4]
libMGL needs a Makefile build.... Xcodebuilds are just too slow.

**Comment by conversy** [comment]
please check out the recently added Makefile, together with my PR. Or wait a little the PR to be accepted, hopefully.

**Comment by conversy** [comment]
@guymadison I suggest you close the issue since there is a Makefile now

**Comment by darkaegisagain** [comment]
fixed by conversy
