### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by r58Playz** [openglonmetal/MGL#48]
When opening the test program, there seems to be a memory leak.
<img width="235" alt="Screen Shot 2022-08-01 at 9 45 45 AM" src="https://user-images.githubusercontent.com/45221816/182200927-f2275506-27de-4f94-a06f-9150989b916d.png">

Could be caused by my viewport PR, testing.

EDIT:
There still seems to be a leak.
<img width="235" alt="Screen Shot 2022-08-01 at 9 48 41 AM" src="https://user-images.githubusercontent.com/45221816/182201454-de1aea29-bb33-4007-9273-4079b337bc81.png">
<img width="235" alt="Screen Shot 2022-08-01 at 9 48 53 AM" src="https://user-images.githubusercontent.com/45221816/182201459-8ad98088-884b-4e53-90ac-a1f8885ec6a4.png">

**Comment by r58Playz** [comment]
Seems to occur when the test program gets hidden by other windows.

**Comment by darkaegisagain** [comment]
Yes I noticed that also, but I never fixed it... it has to do with surface allocation in Metal...

**Comment by r58Playz** [comment]
I think I fixed the major leak, but there are multiple other leaks according to the Leaks instrument.
They're related to `createGLMContext` and `glslang`
<img width="978" alt="Screen Shot 2022-08-02 at 7 27 11 AM" src="https://user-images.githubusercontent.com/45221816/182399369-d99f6276-4275-4a96-b230-26f70188e4ae.png">

**Comment by darkaegisagain** [comment]
Good job.. I tried leaks but it was crashing (which I found out later was due to some advanced memory tracking settings for debugging).

Thanks
