### ISSUE TITLE
MGL as an EGL platform?

### ISSUE THREAD

**Issue by i509VCB** [openglonmetal/MGL#52]
This issue could probably be summarized as: why did MGL choose to write their own GL platform instead of adapting something else, such as EGL.

And then ramble how EGL could be implemented.

The rationale for providing an MGL platform for EGL would allow app developers to reuse their EGL toolkit support if Linux or EGL on Windows is already supported.

I believe the approach to take for EGL would be to write an extension to provide a new EGL platform and a way to create an EGLSurface from something like a CAMetalLayer.

I understand that EGL is no small task to implement. There are also issues like the bureaucracy if the idea goes beyond experimentation if an MGL EGL platform were to be added to the EGL registry.

**Comment by darkaegisagain** [comment]
MGL was written to expose OpenGL 4.6 functionality on top of Metal, I had no intention of supporting EGL as this was for the desktop and not an embedded device.

It was cleaner to ignore backwards compatible interfaces and just implement OGL 4.6 and above… typical OGL applications only use between 10-20 interface calls in a cyclic update manner so it would be better to to have all the function calls that are not implemented not even available for linking in my opinion.

I hope that helps.

Mike

**Comment by i509VCB** [comment]
Okay, thanks for the explanation.
