### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by cblc** [openglonmetal/MGL#71]
This closed [issue](https://github.com/openglonmetal/MGL/issues/62) mentions that the license is dual and you can choose either LGPL or Apache. For me, LGPL is not an option (you never know when you might need static linking for either technical reasons or from a vendor requirement). MIT/BSD would be perfect. Apache good too.

But, however, looking at the repo, it's defined as LGPL-only, with no mention of the Apache choice. So, what's the license?

You mention you want maximum adoption of the library. If that's the case, then MIT/BSD is the way to go, IMHO.

**Comment by CryptoCrocodile** [comment]
Thanks for opening the thread @cblc . I'd like to chime in and second that. We're considering adoption as well, however, the LGPL/Apache situation is tricky. We'd prefer **MIT/BSD** or **zlib** as well. 

@darkaegisagain if it's OK for you I'd submit a PR with the dual license to MIT or BSD. I think to maximize adoption 2-clause BSD or zlib is the way to go as it frees company from the mandatory disclosure - that's always a breaking point as it might be forgotten accidentally: https://en.wikipedia.org/wiki/Zlib_License

**Comment by jamesdolan** [comment]
If the goal is to increase adoption, LGPL is pretty incompatible with commercial software and signed code distributions and thus incompatible with getting wide adoption. A permissive license (MIT, BSD, ZLIB, etc) I think makes the most sense for making everyone happen. Or maybe dual license if for some reason GPL products don't like that?

Also. The argument that you can just release the object files to a commercial app as evidence that it's workable.... well that's exactly the sort of thing commercial software is trying to avoid. 

Anyways. Really cool project! Hopefully this can help keep
OpenGL alive!

**Comment by conversy** [comment]
@jamesdolan well, I was just answering @cblc 's concerns. Anyway the decision is up to @darkaegisagain, I think he's not against changing the license, he just has... to do it :-) 
I'm (guenuingly) looking forward to witnessing widespread adoption once this is done, as I think this project could really benefit from external contributions...

**Comment by darkaegisagain** [comment]
If someone wants to make the change I will check it in, I don’t have access to my development system at this time of the year.

Mike

**Comment by conversy** [comment]
It seems that you've already updated most if not all source files to include the Apache 2.0 header. I submitted a PR that changes `LICENSE` content from LGPL content to Apache 2.0 content. I think you've already asked all contributors if they are ok with that, so I guess it might only be a matter of merging the PR?

**Comment by conversy** [comment]
yes but since it's an important decision, I was letting you do it instead. Ok, so I'm doing it.

**Comment by darkaegisagain** [comment]
No worries I hope you are enjoying your summerMikeSent from my iPhoneOn Jul 23, 2024, at 8:39 AM, conversy ***@***.***> wrote:﻿
Closed #71 as completed.
